version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - run: git config credential.helper 'cache --timeout=120'
      - run: git config user.email "ysm0622@gmail.com"
      - run: git config user.name "CircleCI Auto Deploy"

      - run: npm run circleci:deploy
